// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: nymo.proto

package pb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PeerHandshake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version    uint32   `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Cohort     uint32   `protobuf:"varint,2,opt,name=cohort,proto3" json:"cohort,omitempty"`
	Pow        uint64   `protobuf:"varint,3,opt,name=pow,proto3" json:"pow,omitempty"`
	PeerTokens [][]byte `protobuf:"bytes,4,rep,name=peerTokens,proto3" json:"peerTokens,omitempty"`
}

func (x *PeerHandshake) Reset() {
	*x = PeerHandshake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerHandshake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerHandshake) ProtoMessage() {}

func (x *PeerHandshake) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerHandshake.ProtoReflect.Descriptor instead.
func (*PeerHandshake) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{0}
}

func (x *PeerHandshake) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PeerHandshake) GetCohort() uint32 {
	if x != nil {
		return x.Cohort
	}
	return 0
}

func (x *PeerHandshake) GetPow() uint64 {
	if x != nil {
		return x.Pow
	}
	return 0
}

func (x *PeerHandshake) GetPeerTokens() [][]byte {
	if x != nil {
		return x.PeerTokens
	}
	return nil
}

type HandshakeOK struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cohort     uint32   `protobuf:"varint,1,opt,name=cohort,proto3" json:"cohort,omitempty"`
	PeerTokens [][]byte `protobuf:"bytes,2,rep,name=peerTokens,proto3" json:"peerTokens,omitempty"`
}

func (x *HandshakeOK) Reset() {
	*x = HandshakeOK{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandshakeOK) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeOK) ProtoMessage() {}

func (x *HandshakeOK) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeOK.ProtoReflect.Descriptor instead.
func (*HandshakeOK) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeOK) GetCohort() uint32 {
	if x != nil {
		return x.Cohort
	}
	return 0
}

func (x *HandshakeOK) GetPeerTokens() [][]byte {
	if x != nil {
		return x.PeerTokens
	}
	return nil
}

type MsgDigest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cohort uint32 `protobuf:"varint,1,opt,name=cohort,proto3" json:"cohort,omitempty"`
	Hash   []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *MsgDigest) Reset() {
	*x = MsgDigest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgDigest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDigest) ProtoMessage() {}

func (x *MsgDigest) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDigest.ProtoReflect.Descriptor instead.
func (*MsgDigest) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{2}
}

func (x *MsgDigest) GetCohort() uint32 {
	if x != nil {
		return x.Cohort
	}
	return 0
}

func (x *MsgDigest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type MsgList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Messages []*MsgDigest `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *MsgList) Reset() {
	*x = MsgList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgList) ProtoMessage() {}

func (x *MsgList) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgList.ProtoReflect.Descriptor instead.
func (*MsgList) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{3}
}

func (x *MsgList) GetMessages() []*MsgDigest {
	if x != nil {
		return x.Messages
	}
	return nil
}

type RequestMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []byte `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *RequestMsg) Reset() {
	*x = RequestMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsg) ProtoMessage() {}

func (x *RequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsg.ProtoReflect.Descriptor instead.
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{4}
}

func (x *RequestMsg) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type RequestPeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token  []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Pow    uint64 `protobuf:"varint,2,opt,name=pow,proto3" json:"pow,omitempty"`
	Cohort uint32 `protobuf:"varint,3,opt,name=cohort,proto3" json:"cohort,omitempty"`
}

func (x *RequestPeer) Reset() {
	*x = RequestPeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPeer) ProtoMessage() {}

func (x *RequestPeer) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPeer.ProtoReflect.Descriptor instead.
func (*RequestPeer) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{5}
}

func (x *RequestPeer) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *RequestPeer) GetPow() uint64 {
	if x != nil {
		return x.Pow
	}
	return 0
}

func (x *RequestPeer) GetCohort() uint32 {
	if x != nil {
		return x.Cohort
	}
	return 0
}

type ResponsePeer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      []byte `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	EncAddress []byte `protobuf:"bytes,2,opt,name=encAddress,proto3" json:"encAddress,omitempty"`
}

func (x *ResponsePeer) Reset() {
	*x = ResponsePeer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePeer) ProtoMessage() {}

func (x *ResponsePeer) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePeer.ProtoReflect.Descriptor instead.
func (*ResponsePeer) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{6}
}

func (x *ResponsePeer) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *ResponsePeer) GetEncAddress() []byte {
	if x != nil {
		return x.EncAddress
	}
	return nil
}

type RealMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SenderID []byte `protobuf:"bytes,2,opt,name=senderID,proto3" json:"senderID,omitempty"` // sender's public key
}

func (x *RealMessage) Reset() {
	*x = RealMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealMessage) ProtoMessage() {}

func (x *RealMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealMessage.ProtoReflect.Descriptor instead.
func (*RealMessage) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{7}
}

func (x *RealMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RealMessage) GetSenderID() []byte {
	if x != nil {
		return x.SenderID
	}
	return nil
}

type EncryptedMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg       []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Signature []byte `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // signed with sender's private key
}

func (x *EncryptedMessage) Reset() {
	*x = EncryptedMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedMessage) ProtoMessage() {}

func (x *EncryptedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedMessage.ProtoReflect.Descriptor instead.
func (*EncryptedMessage) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{8}
}

func (x *EncryptedMessage) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *EncryptedMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetCohort uint32 `protobuf:"varint,1,opt,name=targetCohort,proto3" json:"targetCohort,omitempty"`
	Generated    int64  `protobuf:"varint,2,opt,name=generated,proto3" json:"generated,omitempty"`
	EphemeralPub []byte `protobuf:"bytes,3,opt,name=ephemeralPub,proto3" json:"ephemeralPub,omitempty"` // ephemeral public key
	EncMessage   []byte `protobuf:"bytes,4,opt,name=encMessage,proto3" json:"encMessage,omitempty"`     // shared-key encrypted EncryptedMessage
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{9}
}

func (x *Message) GetTargetCohort() uint32 {
	if x != nil {
		return x.TargetCohort
	}
	return 0
}

func (x *Message) GetGenerated() int64 {
	if x != nil {
		return x.Generated
	}
	return 0
}

func (x *Message) GetEphemeralPub() []byte {
	if x != nil {
		return x.EphemeralPub
	}
	return nil
}

func (x *Message) GetEncMessage() []byte {
	if x != nil {
		return x.EncMessage
	}
	return nil
}

type MsgContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg     []byte `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	MsgHash []byte `protobuf:"bytes,2,opt,name=msgHash,proto3" json:"msgHash,omitempty"`
	Pow     uint64 `protobuf:"varint,3,opt,name=pow,proto3" json:"pow,omitempty"`
}

func (x *MsgContainer) Reset() {
	*x = MsgContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nymo_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgContainer) ProtoMessage() {}

func (x *MsgContainer) ProtoReflect() protoreflect.Message {
	mi := &file_nymo_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgContainer.ProtoReflect.Descriptor instead.
func (*MsgContainer) Descriptor() ([]byte, []int) {
	return file_nymo_proto_rawDescGZIP(), []int{10}
}

func (x *MsgContainer) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *MsgContainer) GetMsgHash() []byte {
	if x != nil {
		return x.MsgHash
	}
	return nil
}

func (x *MsgContainer) GetPow() uint64 {
	if x != nil {
		return x.Pow
	}
	return 0
}

var File_nymo_proto protoreflect.FileDescriptor

var file_nymo_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6e, 0x79, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6e, 0x79,
	0x6d, 0x6f, 0x22, 0x73, 0x0a, 0x0d, 0x50, 0x65, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68,
	0x61, 0x6b, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63,
	0x6f, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x03, 0x70, 0x6f, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0a, 0x70, 0x65, 0x65,
	0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x45, 0x0a, 0x0b, 0x48, 0x61, 0x6e, 0x64, 0x73,
	0x68, 0x61, 0x6b, 0x65, 0x4f, 0x4b, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x68, 0x6f, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0c, 0x52, 0x0a, 0x70, 0x65, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x37,
	0x0a, 0x09, 0x4d, 0x73, 0x67, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6f, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x68,
	0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x36, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2b, 0x0a, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6e, 0x79, 0x6d, 0x6f, 0x2e, 0x4d, 0x73, 0x67, 0x44,
	0x69, 0x67, 0x65, 0x73, 0x74, 0x52, 0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22,
	0x20, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x22, 0x4d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x65, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x68, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x6f, 0x68, 0x6f, 0x72, 0x74,
	0x22, 0x44, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x65, 0x65, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x43, 0x0a, 0x0b, 0x52, 0x65, 0x61, 0x6c, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x42, 0x0a, 0x10, 0x45,
	0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22,
	0x8f, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x0c, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x68, 0x6f, 0x72, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x12, 0x22, 0x0a,
	0x0c, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x75, 0x62, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x75,
	0x62, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x4c, 0x0a, 0x0c, 0x4d, 0x73, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x48, 0x61, 0x73, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x48, 0x61, 0x73, 0x68, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x6f, 0x77, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x70, 0x6f, 0x77, 0x42,
	0x1d, 0x5a, 0x1b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x79,
	0x6d, 0x6f, 0x2d, 0x6e, 0x65, 0x74, 0x2f, 0x6e, 0x79, 0x6d, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nymo_proto_rawDescOnce sync.Once
	file_nymo_proto_rawDescData = file_nymo_proto_rawDesc
)

func file_nymo_proto_rawDescGZIP() []byte {
	file_nymo_proto_rawDescOnce.Do(func() {
		file_nymo_proto_rawDescData = protoimpl.X.CompressGZIP(file_nymo_proto_rawDescData)
	})
	return file_nymo_proto_rawDescData
}

var file_nymo_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_nymo_proto_goTypes = []interface{}{
	(*PeerHandshake)(nil),    // 0: nymo.PeerHandshake
	(*HandshakeOK)(nil),      // 1: nymo.HandshakeOK
	(*MsgDigest)(nil),        // 2: nymo.MsgDigest
	(*MsgList)(nil),          // 3: nymo.MsgList
	(*RequestMsg)(nil),       // 4: nymo.RequestMsg
	(*RequestPeer)(nil),      // 5: nymo.RequestPeer
	(*ResponsePeer)(nil),     // 6: nymo.ResponsePeer
	(*RealMessage)(nil),      // 7: nymo.RealMessage
	(*EncryptedMessage)(nil), // 8: nymo.EncryptedMessage
	(*Message)(nil),          // 9: nymo.Message
	(*MsgContainer)(nil),     // 10: nymo.MsgContainer
}
var file_nymo_proto_depIdxs = []int32{
	2, // 0: nymo.MsgList.messages:type_name -> nymo.MsgDigest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nymo_proto_init() }
func file_nymo_proto_init() {
	if File_nymo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nymo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerHandshake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandshakeOK); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgDigest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePeer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EncryptedMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nymo_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nymo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nymo_proto_goTypes,
		DependencyIndexes: file_nymo_proto_depIdxs,
		MessageInfos:      file_nymo_proto_msgTypes,
	}.Build()
	File_nymo_proto = out.File
	file_nymo_proto_rawDesc = nil
	file_nymo_proto_goTypes = nil
	file_nymo_proto_depIdxs = nil
}
